namespace Sample.Core;

public static partial class SDL
{
    public enum InitFlags : uint
    {
        Timer = 0x00000001,
        Audio = 0x00000010,
        Video = 0x00000020,
        Joystick = 0x00000200,
        HapTic = 0x00001000,
        GameController = 0x00002000,
        Events = 0x00004000,
        Sensor = 0x00008000,
        NoParachute = 0x00100000,
        Everything = Timer | Audio | Video | Events | Joystick | HapTic | GameController | Sensor
    }

    public enum MessageBoxFlags : uint
    {
        Error = 0x00000010,
        Warning = 0x00000020,
        Information = 0x00000040,
        ButtonsLeftToRight = 0x00000080,
        ButtonsRightToLeft = 0x00000100
    }

    public enum WindowFlags : uint
    {
        FullScreen = 0x00000001,
        OpenGL = 0x00000002,
        Shown = 0x00000004,
        Hidden = 0x00000008,
        Borderless = 0x00000010,
        Resizable = 0x00000020,
        Minimized = 0x00000040,
        Maximized = 0x00000080,
        MouseGrabbed = 0x00000100,
        InputFocus = 0x00000200,
        MouseFocus = 0x00000400,
        FullScreenDesktop = (FullScreen | 0x00001000),
        Foreign = 0x00000800,
        AllowHighDPI = 0x00002000,
        MouseCapture = 0x00004000,
        AlwaysOnTop = 0x00008000,
        SkipTaskbar = 0x00010000,
        Utility = 0x00020000,
        ToolTip = 0x00040000,
        PopupMenu = 0x00080000,
        KeyboardGrabbed = 0x00100000,
        Vulkan = 0x10000000,
        Metal = 0x20000000,
        InputGrabbed = MouseGrabbed
    }

    public enum RendererFlags : uint
    {
        Software = 0x00000001,
        Accelerated = 0x00000002,
        PresentVSync = 0x00000004,
        TargetTexture = 0x00000008
    }

    public enum EventType : uint
    {
        FirstEvent = 0,
        Quit = 0x100,
        AppTerminating,
        AppLowMemory,
        AppWillEnterBackground,
        AppDidEnterBackground,
        AppWillEnterForeground,
        AppDidEnterForeground,
        LocaleChanged,
        DisplayEvent = 0x150,
        WindowEvent = 0x200,
        SysWMEvent,
        KeyDown = 0x300,
        KeyUp,
        TextEditing,
        TextInput,
        KeyMapChanged,
        TextEditingExt,
        MouseMotion = 0x400,
        MouseButtonDown,
        MouseButtonUp,
        MouseWheel,
        JoyAxisMotion = 0x600,
        JoyBallMotion,
        JoyHatMotion,
        JoyButtonDown,
        JoyButtonUp,
        JoyDeviceAdded,
        JoyDeviceRemoved,
        JoyBatteryUpdated,
        ControllerAxisMotion = 0x650,
        ControllerButtonDown,
        ControllerButtonUp,
        ControllerDeviceAdded,
        ControllerDeviceRemoved,
        ControllerDeviceRemapped,
        ControllerTouchPadDown,
        ControllerTouchPadMotion,
        ControllerTouchPadUp,
        ControllerSensorUpdate,
        ControllerUpdateCompleteReservedForSDL3,
        ControllerSteamHandleUpdated,
        FingerDown = 0x700,
        FingerUp,
        FingerMotion,
        DollarGesture = 0x800,
        DollarRecord,
        MultiGesture,
        ClipboardUpdate = 0x900,
        DropFile = 0x1000,
        DropText,
        DropBegin,
        DropComplete,
        AudioDeviceAdded = 0x1100,
        AudioDeviceRemoved,
        SensorUpdate = 0x1200,
        RenderTargetsReset = 0x2000,
        RenderDeviceReset,
        PollSentinel = 0x7F00,
        UserEvent = 0x8000,
        LastEvent = 0xFFFF
    }

    public enum PressState : byte
    {
        Released = 0,
        Pressed = 1
    }

    public enum Keymod : ushort
    {
        None = 0x0000,
        LShift = 0x0001,
        RShift = 0x0002,
        LCtrl = 0x0040,
        RCtrl = 0x0080,
        LAlt = 0x0100,
        RAlt = 0x0200,
        LGui = 0x0400,
        RGui = 0x0800,
        Num = 0x1000,
        Caps = 0x2000,
        Mode = 0x4000,
        Scroll = 0x8000,
        Ctrl = LCtrl | RCtrl,
        Shift = LShift | RShift,
        Alt = LAlt | RAlt,
        Gui = LGui | RGui,
        Reserved = Scroll
    }

    public enum Scancode : int
    {
        Unknown = 0,
        A = 4,
        B = 5,
        C = 6,
        D = 7,
        E = 8,
        F = 9,
        G = 10,
        H = 11,
        I = 12,
        J = 13,
        K = 14,
        L = 15,
        M = 16,
        N = 17,
        O = 18,
        P = 19,
        Q = 20,
        R = 21,
        S = 22,
        T = 23,
        U = 24,
        V = 25,
        W = 26,
        X = 27,
        Y = 28,
        Z = 29,
        Digit1 = 30,
        Digit2 = 31,
        Digit3 = 32,
        Digit4 = 33,
        Digit5 = 34,
        Digit6 = 35,
        Digit7 = 36,
        Digit8 = 37,
        Digit9 = 38,
        Digit0 = 39,
        Return = 40,
        Escape = 41,
        Backspace = 42,
        Tab = 43,
        Space = 44,
        Minus = 45,
        Equals = 46,
        LeftBracket = 47,
        RightBracket = 48,
        Backslash = 49,
        Nonushash = 50,
        Semicolon = 51,
        Apostrophe = 52,
        Grave = 53,
        Comma = 54,
        Period = 55,
        Slash = 56,
        CapsLock = 57,
        F1 = 58,
        F2 = 59,
        F3 = 60,
        F4 = 61,
        F5 = 62,
        F6 = 63,
        F7 = 64,
        F8 = 65,
        F9 = 66,
        F10 = 67,
        F11 = 68,
        F12 = 69,
        PrintScreen = 70,
        ScrollLock = 71,
        Pause = 72,
        Insert = 73,
        Home = 74,
        PageUp = 75,
        Delete = 76,
        End = 77,
        PageDown = 78,
        Right = 79,
        Left = 80,
        Down = 81,
        Up = 82,
        NumLockClear = 83,
        KpDivide = 84,
        KpMultiply = 85,
        KpMinus = 86,
        KpPlus = 87,
        KpEnter = 88,
        Kp1 = 89,
        Kp2 = 90,
        Kp3 = 91,
        Kp4 = 92,
        Kp5 = 93,
        Kp6 = 94,
        Kp7 = 95,
        Kp8 = 96,
        Kp9 = 97,
        Kp0 = 98,
        KpPeriod = 99,
        NonusBackslash = 100,
        Application = 101,
        Power = 102,
        KpEquals = 103,
        F13 = 104,
        F14 = 105,
        F15 = 106,
        F16 = 107,
        F17 = 108,
        F18 = 109,
        F19 = 110,
        F20 = 111,
        F21 = 112,
        F22 = 113,
        F23 = 114,
        F24 = 115,
        Execute = 116,
        Help = 117,
        Menu = 118,
        Select = 119,
        Stop = 120,
        Again = 121,
        Undo = 122,
        Cut = 123,
        Copy = 124,
        Paste = 125,
        Find = 126,
        Mute = 127,
        VolumeUp = 128,
        VolumeDown = 129,
        KpComma = 133,
        KpEqualsAs400 = 134,
        International1 = 135,
        International2 = 136,
        International3 = 137,
        International4 = 138,
        International5 = 139,
        International6 = 140,
        International7 = 141,
        International8 = 142,
        International9 = 143,
        Lang1 = 144,
        Lang2 = 145,
        Lang3 = 146,
        Lang4 = 147,
        Lang5 = 148,
        Lang6 = 149,
        Lang7 = 150,
        Lang8 = 151,
        Lang9 = 152,
        Alterase = 153,
        SysReq = 154,
        Cancel = 155,
        Clear = 156,
        Prior = 157,
        Return2 = 158,
        Separator = 159,
        Out = 160,
        Oper = 161,
        ClearAgain = 162,
        CrSel = 163,
        Exsel = 164,
        Kp00 = 176,
        Kp000 = 177,
        ThousandsSeparator = 178,
        DecimalSeparator = 179,
        CurrencyUnit = 180,
        CurrencySubUnit = 181,
        KpLeftParen = 182,
        KpRightParen = 183,
        KpLeftBrace = 184,
        KpRightBrace = 185,
        KpTab = 186,
        KpBackspace = 187,
        KpA = 188,
        KpB = 189,
        KpC = 190,
        KpD = 191,
        KpE = 192,
        KpF = 193,
        KpXor = 194,
        KpPower = 195,
        KpPercent = 196,
        KpLess = 197,
        KpGreater = 198,
        KpAmpersand = 199,
        KpDblAmpersand = 200,
        KpVerticalBar = 201,
        KpDblVerticalBar = 202,
        KpColon = 203,
        KpHash = 204,
        KpSpace = 205,
        KpAt = 206,
        KpExclam = 207,
        KpMemStore = 208,
        KpMemRecall = 209,
        KpMemClear = 210,
        KpMemAdd = 211,
        KpMemSubtract = 212,
        KpMemMultiply = 213,
        KpMemDivide = 214,
        KpPlusMinus = 215,
        KpClear = 216,
        KpClearEntry = 217,
        KpBinary = 218,
        KpOctal = 219,
        KpDecimal = 220,
        KpHexadecimal = 221,
        LCtrl = 224,
        LShift = 225,
        LAlt = 226,
        LGui = 227,
        RCtrl = 228,
        RShift = 229,
        RAlt = 230,
        RGui = 231,
        Mode = 257,
        AudioNext = 258,
        AudioPrev = 259,
        AudioStop = 260,
        AudioPlay = 261,
        AudioMute = 262,
        MediaSelect = 263,
        WWW = 264,
        Mail = 265,
        Calculator = 266,
        Computer = 267,
        AcSearch = 268,
        AcHome = 269,
        AcBack = 270,
        AcForward = 271,
        AcStop = 272,
        AcRefresh = 273,
        AcBookMarks = 274,
        BrightnessDown = 275,
        BrightnessUp = 276,
        DisplaySwitch = 277,
        KbDillumToggle = 278,
        KbDillumDown = 279,
        KbDillumUp = 280,
        Eject = 281,
        Sleep = 282,
        App1 = 283,
        App2 = 284,
        AudioRewind = 285,
        AudioFastForward = 286,
        SoftLeft = 287,
        SoftRight = 288,
        Call = 289,
        EndCall = 290,
        NumScancodes = 512
    }

    public enum KeyCode : int
    {
        Unknown = 0,
        Return = '\r',
        Escape = '\x1B',
        Backspace = '\b',
        Tab = '\t',
        Space = ' ',
        Exclaim = '!',
        QuoteDbl = '"',
        Hash = '#',
        Percent = '%',
        Dollar = '$',
        Ampersand = '&',
        Quote = '\'',
        LeftParen = '(',
        RightParen = ')',
        Asterisk = '*',
        Plus = '+',
        Comma = ',',
        Minus = '-',
        Period = '.',
        Slash = '/',
        Digit0 = '0',
        Digit1 = '1',
        Digit2 = '2',
        Digit3 = '3',
        Digit4 = '4',
        Digit5 = '5',
        Digit6 = '6',
        Digit7 = '7',
        Digit8 = '8',
        Digit9 = '9',
        Colon = ':',
        Semicolon = ';',
        Less = '<',
        Equals = '=',
        Greater = '>',
        Question = '?',
        At = '@',
        LeftBracket = '[',
        Backslash = '\\',
        RightBracket = ']',
        Caret = '^',
        Underscore = '_',
        BackQuote = '`',
        a = 'a',
        b = 'b',
        c = 'c',
        d = 'd',
        e = 'e',
        f = 'f',
        g = 'g',
        h = 'h',
        i = 'i',
        j = 'j',
        k = 'k',
        l = 'l',
        m = 'm',
        n = 'n',
        o = 'o',
        p = 'p',
        q = 'q',
        r = 'r',
        s = 's',
        t = 't',
        u = 'u',
        v = 'v',
        w = 'w',
        x = 'x',
        y = 'y',
        z = 'z',
        Capslock = Scancode.CapsLock | ScancodeMask,
        F1 = Scancode.F1 | ScancodeMask,
        F2 = Scancode.F2 | ScancodeMask,
        F3 = Scancode.F3 | ScancodeMask,
        F4 = Scancode.F4 | ScancodeMask,
        F5 = Scancode.F5 | ScancodeMask,
        F6 = Scancode.F6 | ScancodeMask,
        F7 = Scancode.F7 | ScancodeMask,
        F8 = Scancode.F8 | ScancodeMask,
        F9 = Scancode.F9 | ScancodeMask,
        F10 = Scancode.F10 | ScancodeMask,
        F11 = Scancode.F11 | ScancodeMask,
        F12 = Scancode.F12 | ScancodeMask,
        PrintScreen = Scancode.PrintScreen | ScancodeMask,
        ScrollLock = Scancode.ScrollLock | ScancodeMask,
        Pause = Scancode.Pause | ScancodeMask,
        Insert = Scancode.Insert | ScancodeMask,
        Home = Scancode.Home | ScancodeMask,
        PageUp = Scancode.PageUp | ScancodeMask,
        Delete = '\x7F',
        End = Scancode.End | ScancodeMask,
        PageDown = Scancode.PageDown | ScancodeMask,
        Right = Scancode.Right | ScancodeMask,
        Left = Scancode.Left | ScancodeMask,
        Down = Scancode.Down | ScancodeMask,
        Up = Scancode.Up | ScancodeMask,
        NumLockClear = Scancode.NumLockClear | ScancodeMask,
        KpDivide = Scancode.KpDivide | ScancodeMask,
        KpMultiply = Scancode.KpMultiply | ScancodeMask,
        KpMinus = Scancode.KpMinus | ScancodeMask,
        KpPlus = Scancode.KpPlus | ScancodeMask,
        KpEnter = Scancode.KpEnter | ScancodeMask,
        Kp1 = Scancode.Kp1 | ScancodeMask,
        Kp2 = Scancode.Kp2 | ScancodeMask,
        Kp3 = Scancode.Kp3 | ScancodeMask,
        Kp4 = Scancode.Kp4 | ScancodeMask,
        Kp5 = Scancode.Kp5 | ScancodeMask,
        Kp6 = Scancode.Kp6 | ScancodeMask,
        Kp7 = Scancode.Kp7 | ScancodeMask,
        Kp8 = Scancode.Kp8 | ScancodeMask,
        Kp9 = Scancode.Kp9 | ScancodeMask,
        Kp0 = Scancode.Kp0 | ScancodeMask,
        KpPeriod = Scancode.KpPeriod | ScancodeMask,
        Application = Scancode.Application | ScancodeMask,
        Power = Scancode.Power | ScancodeMask,
        KpEquals = Scancode.KpEquals | ScancodeMask,
        F13 = Scancode.F13 | ScancodeMask,
        F14 = Scancode.F14 | ScancodeMask,
        F15 = Scancode.F15 | ScancodeMask,
        F16 = Scancode.F16 | ScancodeMask,
        F17 = Scancode.F17 | ScancodeMask,
        F18 = Scancode.F18 | ScancodeMask,
        F19 = Scancode.F19 | ScancodeMask,
        F20 = Scancode.F20 | ScancodeMask,
        F21 = Scancode.F21 | ScancodeMask,
        F22 = Scancode.F22 | ScancodeMask,
        F23 = Scancode.F23 | ScancodeMask,
        F24 = Scancode.F24 | ScancodeMask,
        Execute = Scancode.Execute | ScancodeMask,
        Help = Scancode.Help | ScancodeMask,
        Menu = Scancode.Menu | ScancodeMask,
        Select = Scancode.Select | ScancodeMask,
        Stop = Scancode.Stop | ScancodeMask,
        Again = Scancode.Again | ScancodeMask,
        Undo = Scancode.Undo | ScancodeMask,
        Cut = Scancode.Cut | ScancodeMask,
        Copy = Scancode.Copy | ScancodeMask,
        Paste = Scancode.Paste | ScancodeMask,
        Find = Scancode.Find | ScancodeMask,
        Mute = Scancode.Mute | ScancodeMask,
        VolumeUp = Scancode.VolumeUp | ScancodeMask,
        VolumeDown = Scancode.VolumeDown | ScancodeMask,
        KpComma = Scancode.KpComma | ScancodeMask,
        KpEqualsAs400 = Scancode.KpEqualsAs400 | ScancodeMask,
        Alterase = Scancode.Alterase | ScancodeMask,
        SysReq = Scancode.SysReq | ScancodeMask,
        Cancel = Scancode.Cancel | ScancodeMask,
        Clear = Scancode.Clear | ScancodeMask,
        Prior = Scancode.Prior | ScancodeMask,
        Return2 = Scancode.Return2 | ScancodeMask,
        Separator = Scancode.Separator | ScancodeMask,
        Out = Scancode.Out | ScancodeMask,
        Oper = Scancode.Oper | ScancodeMask,
        ClearAgain = Scancode.ClearAgain | ScancodeMask,
        CrSel = Scancode.CrSel | ScancodeMask,
        Exsel = Scancode.Exsel | ScancodeMask,
        Kp00 = Scancode.Kp00 | ScancodeMask,
        Kp000 = Scancode.Kp000 | ScancodeMask,
        ThousandsSeparator = Scancode.ThousandsSeparator | ScancodeMask,
        DecimalSeparator = Scancode.DecimalSeparator | ScancodeMask,
        CurrencyUnit = Scancode.CurrencyUnit | ScancodeMask,
        CurrencySubUnit = Scancode.CurrencySubUnit | ScancodeMask,
        KpLeftParen = Scancode.KpLeftParen | ScancodeMask,
        KpRightParen = Scancode.KpRightParen | ScancodeMask,
        KpLeftBrace = Scancode.KpLeftBrace | ScancodeMask,
        KpRightBrace = Scancode.KpRightBrace | ScancodeMask,
        KpTab = Scancode.KpTab | ScancodeMask,
        KpBackspace = Scancode.KpBackspace | ScancodeMask,
        KpA = Scancode.KpA | ScancodeMask,
        KpB = Scancode.KpB | ScancodeMask,
        KpC = Scancode.KpC | ScancodeMask,
        KpD = Scancode.KpD | ScancodeMask,
        KpE = Scancode.KpE | ScancodeMask,
        KpF = Scancode.KpF | ScancodeMask,
        KpXor = Scancode.KpXor | ScancodeMask,
        KpPower = Scancode.KpPower | ScancodeMask,
        KpPercent = Scancode.KpPercent | ScancodeMask,
        KpLess = Scancode.KpLess | ScancodeMask,
        KpGreater = Scancode.KpGreater | ScancodeMask,
        KpAmpersand = Scancode.KpAmpersand | ScancodeMask,
        KpDblAmpersand = Scancode.KpDblAmpersand | ScancodeMask,
        KpVerticalBar = Scancode.KpVerticalBar | ScancodeMask,
        KpDblVerticalBar = Scancode.KpDblVerticalBar | ScancodeMask,
        KpColon = Scancode.KpColon | ScancodeMask,
        KpHash = Scancode.KpHash | ScancodeMask,
        KpSpace = Scancode.KpSpace | ScancodeMask,
        KpAt = Scancode.KpAt | ScancodeMask,
        KpExclam = Scancode.KpExclam | ScancodeMask,
        KpMemStore = Scancode.KpMemStore | ScancodeMask,
        KpMemRecall = Scancode.KpMemRecall | ScancodeMask,
        KpMemClear = Scancode.KpMemClear | ScancodeMask,
        KpMemAdd = Scancode.KpMemAdd | ScancodeMask,
        KpMemSubtract = Scancode.KpMemSubtract | ScancodeMask,
        KpMemMultiply = Scancode.KpMemMultiply | ScancodeMask,
        KpMemDivide = Scancode.KpMemDivide | ScancodeMask,
        KpPlusMinus = Scancode.KpPlusMinus | ScancodeMask,
        KpClear = Scancode.KpClear | ScancodeMask,
        KpClearEntry = Scancode.KpClearEntry | ScancodeMask,
        KpBinary = Scancode.KpBinary | ScancodeMask,
        KpOctal = Scancode.KpOctal | ScancodeMask,
        KpDecimal = Scancode.KpDecimal | ScancodeMask,
        KpHexadecimal = Scancode.KpHexadecimal | ScancodeMask,
        LCtrl = Scancode.LCtrl | ScancodeMask,
        LShift = Scancode.LShift | ScancodeMask,
        LAlt = Scancode.LAlt | ScancodeMask,
        LGui = Scancode.LGui | ScancodeMask,
        RCtrl = Scancode.RCtrl | ScancodeMask,
        RShift = Scancode.RShift | ScancodeMask,
        RAlt = Scancode.RAlt | ScancodeMask,
        RGui = Scancode.RGui | ScancodeMask,
        Mode = Scancode.Mode | ScancodeMask,
        AudioNext = Scancode.AudioNext | ScancodeMask,
        AudioPrev = Scancode.AudioPrev | ScancodeMask,
        AudioStop = Scancode.AudioStop | ScancodeMask,
        AudioPlay = Scancode.AudioPlay | ScancodeMask,
        AudioMute = Scancode.AudioMute | ScancodeMask,
        MediaSelect = Scancode.MediaSelect | ScancodeMask,
        WWW = Scancode.WWW | ScancodeMask,
        Mail = Scancode.Mail | ScancodeMask,
        Calculator = Scancode.Calculator | ScancodeMask,
        Computer = Scancode.Computer | ScancodeMask,
        AcSearch = Scancode.AcSearch | ScancodeMask,
        AcHome = Scancode.AcHome | ScancodeMask,
        AcBack = Scancode.AcBack | ScancodeMask,
        AcForward = Scancode.AcForward | ScancodeMask,
        AcStop = Scancode.AcStop | ScancodeMask,
        AcRefresh = Scancode.AcRefresh | ScancodeMask,
        AcBookMarks = Scancode.AcBookMarks | ScancodeMask,
        BrightnessDown = Scancode.BrightnessDown | ScancodeMask,
        BrightnessUp = Scancode.BrightnessUp | ScancodeMask,
        DisplaySwitch = Scancode.DisplaySwitch | ScancodeMask,
        KbDillumToggle = Scancode.KbDillumToggle | ScancodeMask,
        KbDillumDown = Scancode.KbDillumDown | ScancodeMask,
        KbDillumUp = Scancode.KbDillumUp | ScancodeMask,
        Eject = Scancode.Eject | ScancodeMask,
        Sleep = Scancode.Sleep | ScancodeMask,
        App1 = Scancode.App1 | ScancodeMask,
        App2 = Scancode.App2 | ScancodeMask,
        AudioRewind = Scancode.AudioRewind | ScancodeMask,
        AudioFastForward = Scancode.AudioFastForward | ScancodeMask,
        SoftLeft = Scancode.SoftLeft | ScancodeMask,
        SoftRight = Scancode.SoftRight | ScancodeMask,
        Call = Scancode.Call | ScancodeMask,
        EndCall = Scancode.EndCall | ScancodeMask,
    }

    public enum MouseWheelDirection : uint
    {
        Normal,
        Flipped
    }
}
