name: Test
on: [ push ]
jobs:
  test:
    permissions:
      checks: write
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Run tests
      run: dotnet test Sample.Tests/Sample.Tests.csproj --logger trx --results-directory "TestResults-${{ matrix.os }}"
    - name: Report tests
      if: ${{ always() }}
      uses: dorny/test-reporter@v1.9.1
      with:
        name: Test report for ${{ matrix.os }} 
        path: "TestResults-${{ matrix.os }}/**.trx"
        reporter: dotnet-trx
